version: "3.9"

services:
  postgres_db:
    image: 'postgres:15.1-alpine'
    container_name: postgres_db
    environment:
        SPRING_DATASOURCE_HOST: localhost
        SPRING_DATASOURCE_PORT: 5432
        SPRING_DATASOURCE_DATABASE: credit-service
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  credit-service:
    container_name: credit-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_HOST: localhost
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: credit-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always
    volumes:
      - /logs/credit:/logs
    networks:
      - a-tink-test
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  a-tink-test:
    external: true
    driver: bridge
